--- #YAML:1.0
name:                DataWarehouse
version:             0.01
abstract:            Perl Data Warehouse Toolkit
license:             perl
author:              
    - Nelson Ferraz <nferraz@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
